apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "divvun-worker-tts.fullname" . }}
  labels:
    {{- include "divvun-worker-tts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "divvun-worker-tts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "divvun-worker-tts.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        env:
        - name: ADDRESS
          value: {{ .Values.env.ADDRESS | quote }}
        args:
        - "/app/bundles"
        volumeMounts:
        - name: bundles-volume
          mountPath: /app/bundles
          readOnly: true
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
      volumes:
      - name: bundles-volume
        persistentVolumeClaim:
          claimName: {{ .Values.bundle.pvcName }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}